<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Страница аутентификации</title>
</head>
<body>
<h1>Пожалуйста, представьтесь!</h1>
<h2>Аутентификация</h2>
<form action="/auth" method="post"> <!--TODO-->
    Email:<br>
    <input type="text" name="email" value="user@mail.ru">
    <br>
    Password:<br>
    <input type="text" name="password" value="123">
    <br><br>
    <input type="submit" value="Submit">
</form>
</body>
</html>